# deploy a cluster
---

- hosts: nodes
  any_errors_fatal: true  # abort on first error
  tasks:
  - name: "run user dbus (actually useful only for development: bowl service file requires it anyway)"
    systemd:
      name: dbus.service
      scope: user
      state: started
    tags:
    - user_dbus

  - name: create systemd user units dir
    file: path="{{ ansible_env.HOME }}/.config/systemd/user/" state=directory
    tags:
    - create_systemd_user_unit_dir

  - name: instantiate bowl unit file
    template:
      src: templates/shardman-bowl.service.j2
      dest: "{{ ansible_env.HOME }}/.config/systemd/user/shardman-bowl-{{ cluster_name }}.service"
    tags:
    - bowl_unit
    - units

  - name: destoy data dir "{{ data_dir }}"
    file: path="{{ data_dir }}" state=absent
    tags:
      - destory_data_dir
    # during development, running daemons constantly write into this dir, so try
    # multiple times and ignore errors
    loop: [1, 2, 3]
    ignore_errors: yes

  - name: create data dir
    file: path="{{ data_dir }}" state=directory
    tags:
      - create_data_dir

  - name: prepare bowls env file
    template:
      src: templates/bowl.env.j2
      dest: "{{ data_dir }}/bowl-{{ cluster_name }}.env"
    tags:
    - bowl_env
    - units

  - name: instantiate monitor unit file
    template:
      src: templates/shardman-monitor.service.j2
      dest: "{{ ansible_env.HOME }}/.config/systemd/user/shardman-monitor-{{ cluster_name }}.service"
    tags:
    - monitor_unit
    - units

  - name: instantiate keeper unit file
    template:
      src: templates/shardman-keeper@.service.j2
      dest: "{{ ansible_env.HOME }}/.config/systemd/user/shardman-keeper-{{ cluster_name }}@.service"
    tags:
    - keeper_unit
    - units

  - name: instantiate sentinel unit file
    template:
      src: templates/shardman-sentinel@.service.j2
      dest: "{{ ansible_env.HOME }}/.config/systemd/user/shardman-sentinel-{{ cluster_name }}@.service"
    tags:
    - sentinel_unit
    - units

  - name: instantiate proxy unit file
    template:
      src: templates/shardman-proxy@.service.j2
      dest: "{{ ansible_env.HOME }}/.config/systemd/user/shardman-proxy-{{ cluster_name }}@.service"
    tags:
    - proxy_unit
    - units

  - name: reload systemd
    systemd:
      daemon_reload: yes
      scope: user

  - name: instantiate spec file
    template:
      src: templates/shmnspec.json.j2
      dest: "{{ ansible_env.HOME }}/shmnspec.json"
    tags:
      instantiate_spec

  - name: start bowls
    systemd:
      name: shardman-bowl-{{ cluster_name }}.service
      scope: user
      state: restarted
      enabled: yes
    tags:
      start_bowl

  - name: init cluster
    command: shardman-ladle --store-endpoints {{ lookup('template', 'etcd_endpoints.j2') }} --cluster-name {{ cluster_name }} init -f shmnspec.json
    run_once: true
    tags:
    - init

  - name: "add nodes: shardman-ladle --store-endpoints {{ lookup('template', 'etcd_endpoints.j2') }} --cluster-name {{ cluster_name }} addnodes -n {{ lookup('template', 'comma_separated_nodes.j2') }}"
    command: shardman-ladle --store-endpoints {{ lookup('template', 'etcd_endpoints.j2') }} --cluster-name {{ cluster_name }} addnodes -n {{ lookup('template', 'comma_separated_nodes.j2') }}
    run_once: true
    tags:
    - add_nodes