---
# install stolon

- name: clone stolon sources {{ stolon_repo }}/{{ stolon_version_tag }}
  git: repo="{{ stolon_repo }}"
    dest="{{ stolon_src }}"
    version="{{ stolon_version_tag }}"
    depth=20
    accept_hostkey=True
    force=yes
  tags:
    - stolon

- name: build stolon
  command: "make"
  args:
    chdir: "{{ stolon_src }}"
  tags:
    - stolon

- name: add stolon binaries to PATH in .bashrc
  lineinfile:
    path: "{{ ansible_env.HOME}}/.bashrc"
    line: 'export PATH=$PATH:{{ stolon_src }}/bin'
    # important, otherwise not read in non-interactive sessions
    insertbefore: BOF
  tags:
    - stolon
