all:
	goimports -w .
	go install postgrespro.ru/hodgepodge/cmd/hpctl
	go install postgrespro.ru/hodgepodge/cmd/hpmon

rebuild:
	go install -a postgrespro.ru/hodgepodge/cmd/hpctl
	go install -a postgrespro.ru/hodgepodge/cmd/hpmon
